export const movies = [
  {
    movieId: 1,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
  {
    movieId: 2,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
  {
    movieId: 3,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
  {
    movieId: 4,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
  {
    movieId: 5,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
  {
    movieId: 6,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
  {
    movieId: 7,
    nameRU: "Фильм",
    nameEN: "Movie",
    duration: 125,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    trailerLink: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkpA6yExDDnaDjgcAfpZuDXNTI2bcR8ePFsw&usqp=CAU",
  },
];
