const BASE_URL = "https://api.soy.movies.nomoredomains.icu";
const MOVIES_API_URL = 'https://api.nomoreparties.co/';

const SHORT_MOVIE_DURATION = 40;

const INITIAL_CARDS_COUNT_1280 = 12;
const INITIAL_CARDS_COUNT_800 = 8;
const INITIAL_CARDS_COUNT_600 = 5;

const CARDS_INCREMENT_1280 = 3;
const CARDS_INCREMENT_800 = 2;

export { BASE_URL, MOVIES_API_URL, SHORT_MOVIE_DURATION,
  INITIAL_CARDS_COUNT_1280, INITIAL_CARDS_COUNT_800, INITIAL_CARDS_COUNT_600,
  CARDS_INCREMENT_1280, CARDS_INCREMENT_800 };
